"""scripts/analyze_disambiguation.py tests (Phase-1 disambiguation, Task 3).

CPU-only, synthetic sidecars. The comparison section consumes raw sidecar
JSONs (same reading convention as scripts/analyze_phase1.py); the HVP
section goes through the schema-validating loader, so its fixture is
generated by a real MatrixTracker.

Seeds: dev seeds only (>= 1000).
"""

import importlib.util
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

import numpy as np
import pytest
import torch

from src.instrument.schema import INSTRUMENTATION_SCHEMA_VERSION, write_sidecar
from src.instrument.tracker import MatrixTracker


def _load_module(name, relpath):
    spec = importlib.util.spec_from_file_location(name, REPO_ROOT / relpath)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


ad = _load_module("analyze_disambiguation", "scripts/analyze_disambiguation.py")


# ---------------------------------------------------------------- fixtures


def _direction(kind, index, rho_value, steps, total_steps=200):
    n = len(steps)
    return {
        "index": index,
        "kind": kind,
        "s": [0.0] * total_steps,  # per observed step (matrix "steps")
        "reset_steps": [],
        "refresh_alignment": {"step": [], "value": []},
        "sigma": {"step": [], "value": []},
        "lambda_hvp": {"step": [], "value": []},
        "per_beta": {
            "0.9": {
                "step": list(steps),
                "regime": ["noise"] * n,
                "mu": [0.0] * n,
                "var": [1.0] * n,
                "rho": [rho_value] * n,
                "t_stat": [0.0] * n,
                "amplitude_ratio": [1.0] * n,
                "implied_eta_lambda": [2.0] * n,
                "ess": [10.0] * n,
                "n_since_reset": [100] * n,
            }
        },
    }


def _sidecar(rho_top, rho_bulk):
    steps = list(range(5, 201, 5))
    return {
        "instrumentation_schema_version": INSTRUMENTATION_SCHEMA_VERSION,
        "betas": ["0.9"],
        "hvp_enabled": False,
        "matrices": {
            "layers.0.conv1.weight": {
                "shape": [8, 8],
                "k1": 1,
                "k2": 1,
                "t_refresh": 50,
                "align_min": 0.9,
                "snapshot_every": 5,
                "steps": list(range(1, 201)),
                "grad_fro_norm": [1.0] * 200,
                "top_sigma_m": [1.0] * 200,
                "refresh_steps": [1, 51, 101, 151],
                "directions": [
                    _direction("top", 0, rho_top, steps),
                    _direction("bulk", 1, rho_bulk, steps),
                ],
            }
        },
    }


@pytest.fixture()
def comparison_dirs(tmp_path):
    """3 baseline runs (top rho=-0.5, bulk rho=0.1 -> all-frac 0.5) vs
    2 with-replacement runs (both rho=0.1 -> all-frac 0.0)."""
    base = tmp_path / "baseline"
    wr = tmp_path / "withrepl"
    base.mkdir()
    wr.mkdir()
    for seed in (1000, 1001, 1002):
        (base / f"run_seed{seed}.instrumentation.json").write_text(
            json.dumps(_sidecar(rho_top=-0.5, rho_bulk=0.1))
        )
    for seed in (1100, 1101):
        (wr / f"run_seed{seed}.instrumentation.json").write_text(
            json.dumps(_sidecar(rho_top=0.1, rho_bulk=0.1))
        )
    return base, wr


@pytest.fixture(scope="module")
def hvp_dir(tmp_path_factory):
    """One schema-valid HVP-enabled sidecar with an oscillating direction and
    varying lambda records (real MatrixTracker, as in the plots tests)."""
    gen = torch.Generator().manual_seed(1700)
    rng = np.random.default_rng(1700)
    m, n = 20, 14
    U0, _ = torch.linalg.qr(torch.randn(m, 3, generator=gen))
    V0, _ = torch.linalg.qr(torch.randn(n, 3, generator=gen))
    M = (
        15.0 * torch.outer(U0[:, 0], V0[:, 0])
        + 7.0 * torch.outer(U0[:, 1], V0[:, 1])
        + 3.0 * torch.outer(U0[:, 2], V0[:, 2])
    )
    tracker = MatrixTracker(
        "layer0",
        (m, n),
        k1=3,
        k2=2,
        t_refresh=40,
        betas=(0.9, 0.99),
        classifier_kwargs=dict(tau_sig=4.0, tau_noise=2.0, rho_osc=0.5, n_min=40),
        snapshot_every=5,
        generator=gen,
    )
    param = torch.zeros(m, n)
    counter = {"n": 0}

    def hvp_fn(p, D):
        counter["n"] += 1
        return 18.0 + 0.5 * (counter["n"] % 5)  # varying lambdas

    for t in range(200):
        c_sig = 1.0 + 0.1 * rng.standard_normal()
        c_osc = 3.0 * ((-1.0) ** t) * (1.0 + 0.02 * rng.standard_normal())
        c_noise = 0.5 * rng.standard_normal()
        G = (
            c_sig * torch.outer(U0[:, 0], V0[:, 0])
            + c_osc * torch.outer(U0[:, 1], V0[:, 1])
            + c_noise * torch.outer(U0[:, 2], V0[:, 2])
        )
        G = G + 0.02 * torch.from_numpy(
            rng.standard_normal((m, n)).astype(np.float32)
        )
        tracker.observe(G, M, hvp_fn=hvp_fn, param=param)
    log = {
        "instrumentation_schema_version": INSTRUMENTATION_SCHEMA_VERSION,
        "betas": ["0.9", "0.99"],
        "hvp_enabled": True,
        "matrices": {"layer0": tracker.to_log()},
    }
    out = tmp_path_factory.mktemp("hvp_sidecars")
    write_sidecar(log, out / "hvp_run_seed1700.json")
    return out


# ------------------------------------------------------------------- tests


def test_sampling_comparison_fractions_and_difference(comparison_dirs, tmp_path):
    base, wr = comparison_dirs
    out_json = tmp_path / "report.json"
    out_md = tmp_path / "report.md"
    rc = ad.main(
        [
            "--baseline", str(base),
            "--with-replacement", str(wr),
            "--n-boot", "200",
            "--out-json", str(out_json),
            "--out-md", str(out_md),
        ]
    )
    assert rc == 0
    report = json.loads(out_json.read_text())
    comp = report["sampling_comparison"]
    assert comp["n_runs"] == {"baseline": 3, "with_replacement": 2}
    assert comp["rho_threshold"] == -0.2

    cells = comp["variants"]["raw"]["cells"]
    by_key = {(c["beta"], c["phase"], c["kind"]): c for c in cells}
    assert len(by_key) == len(cells)  # unique cells
    for phase in (1, 2, 3, 4):
        c = by_key[("0.9", phase, "all")]
        # All runs identical within each set -> degenerate bootstrap CIs.
        assert c["baseline"]["mean_frac"] == pytest.approx(0.5)
        assert c["baseline"]["ci"] == [pytest.approx(0.5), pytest.approx(0.5)]
        assert c["with_replacement"]["mean_frac"] == pytest.approx(0.0)
        d = c["difference_baseline_minus_withrepl"]
        assert d["mean"] == pytest.approx(0.5)
        assert d["ci"] == [pytest.approx(0.5), pytest.approx(0.5)]
        assert by_key[("0.9", phase, "top")]["baseline"]["mean_frac"] == (
            pytest.approx(1.0)
        )
        assert by_key[("0.9", phase, "bulk")]["baseline"]["mean_frac"] == (
            pytest.approx(0.0)
        )
    # 10 snapshots per phase per direction per run.
    c = by_key[("0.9", 1, "all")]
    assert c["baseline"]["n_snapshots_total"] == 3 * 2 * 10
    # Descriptive framing in the markdown header.
    md = out_md.read_text()
    assert "descriptive; no pass/fail" in md
    assert "Sampling ablation" in md


def test_output_is_deterministic(comparison_dirs, tmp_path):
    base, wr = comparison_dirs
    outs = []
    for tag in ("a", "b"):
        oj = tmp_path / f"{tag}.json"
        om = tmp_path / f"{tag}.md"
        ad.main(
            [
                "--baseline", str(base),
                "--with-replacement", str(wr),
                "--n-boot", "100",
                "--out-json", str(oj),
                "--out-md", str(om),
            ]
        )
        outs.append((oj.read_bytes(), om.read_bytes()))
    assert outs[0] == outs[1]


def test_hvp_agreement_stats(hvp_dir, tmp_path):
    out_json = tmp_path / "hvp_report.json"
    rc = ad.main(
        [
            "--hvp", str(hvp_dir),
            "--lr", "0.1",
            "--out-json", str(out_json),
        ]
    )
    assert rc == 0
    report = json.loads(out_json.read_text())
    assert "sampling_comparison" not in report
    cal = report["hvp_calibration"]
    assert cal["lr"] == 0.1
    assert cal["n_runs"] == 1
    for beta in ("0.9", "0.99"):
        e = cal["per_beta"][beta]
        assert e["n_pairs"] > 0
        assert e["median_rel_err"] is not None
        assert e["median_implied"] == pytest.approx(2.0, abs=0.5)
        # lr * lambda in [1.8, 2.05] by construction of hvp_fn.
        assert 1.75 <= e["median_hvp_eta_lambda"] <= 2.1


def test_requires_both_comparison_dirs_or_hvp(tmp_path):
    with pytest.raises(SystemExit):
        ad.main(["--baseline", str(tmp_path)])
    with pytest.raises(SystemExit):
        ad.main([])


def test_hvp_section_refuses_non_hvp_sidecars(comparison_dirs, tmp_path):
    base, _ = comparison_dirs
    with pytest.raises(SystemExit, match="hvp_enabled"):
        ad.main(["--hvp", str(base), "--lr", "0.1"])
